spring:
  application:
    name: soaptask
server:
  port: 8080

vies:
  endpoint: https://ec.europa.eu/taxation_customs/vies/services/checkVatService
  wsdl: https://ec.europa.eu/taxation_customs/vies/checkVatService.wsdl

  timeout:
    connect: 5s
    read: 15s
  retry:
    max-attempts: 3
    delay: 1s
    multiplier: 3.0